spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hr?serverTimezone=GMT%2B0800&useLegacyDatetimeCode=false&useUnicode=true&characterEncoding=UTF-8&useSSL=false&nullCatalogMeansCurrent=true
    username: root
    password: root
#    type: com.mysql.cj.jdbc.MysqlDataSource
#    type: com.alibaba.druid.pool.DruidDataSource
#  autoconfigure:
#    exclude:  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8081
