server:
  port: 8099
spring:
  profiles:
    active: local
  application:
    name: hrsys
  redis:
    host: localhost
    database: 0
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 3000ms
redis:
  key:
    prefix:
      authCode: "authCode-"
    expire:
        time: 120
jwt:
  tokenHeader: Authorization #请求头
  secret: hrsys #秘钥
  expiration: 3600 #过期时间
  tokenHead: 'Bearer ' #JWT负载中拿到开头

#也可以使用-表示多文档块
---
spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrsys?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: "000000"
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml